"""
OCP HTML Report Generator.
Produces a self-contained HTML report from a results JSON file.
"""

from __future__ import annotations

import json
import time
from pathlib import Path

REPORT_TEMPLATE = """<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>OCP Report — {model}</title>
<style>
  :root {{
    --bg: #0d1117; --surface: #161b22; --border: #30363d;
    --text: #e6edf3; --muted: #8b949e; --accent: #58a6ff;
    --green: #3fb950; --yellow: #d29922; --orange: #f0883e; --red: #f85149;
    --purple: #bc8cff; --cyan: #79c0ff;
  }}
  * {{ box-sizing: border-box; margin: 0; padding: 0; }}
  body {{ background: var(--bg); color: var(--text); font-family: 'Segoe UI', system-ui, sans-serif;
         line-height: 1.6; padding: 2rem; }}
  h1 {{ color: var(--accent); font-size: 1.8rem; margin-bottom: 0.25rem; }}
  h2 {{ color: var(--cyan); font-size: 1.2rem; margin: 1.5rem 0 0.75rem; border-bottom: 1px solid var(--border);
       padding-bottom: 0.4rem; }}
  h3 {{ color: var(--muted); font-size: 0.9rem; text-transform: uppercase; letter-spacing: 0.08em;
       margin: 1rem 0 0.5rem; }}
  .subtitle {{ color: var(--muted); font-size: 0.9rem; margin-bottom: 2rem; }}
  .card {{ background: var(--surface); border: 1px solid var(--border); border-radius: 8px;
           padding: 1.25rem; margin-bottom: 1rem; }}
  .level-badge {{ display: inline-block; padding: 0.3rem 0.8rem; border-radius: 20px;
                  font-weight: bold; font-size: 1.1rem; margin: 0.5rem 0; }}
  .level-1 {{ background: #21262d; color: var(--muted); }}
  .level-2 {{ background: #2d2200; color: var(--yellow); }}
  .level-3 {{ background: #1a2d1a; color: var(--green); }}
  .level-4 {{ background: #001d3d; color: var(--cyan); }}
  .level-5 {{ background: #1a0a2e; color: var(--purple); }}
  .grid-2 {{ display: grid; grid-template-columns: 1fr 1fr; gap: 1rem; }}
  .score-row {{ display: flex; align-items: center; gap: 0.75rem; margin: 0.4rem 0; font-size: 0.9rem; }}
  .score-label {{ min-width: 220px; color: var(--muted); }}
  .score-bar-outer {{ flex: 1; background: #21262d; border-radius: 4px; height: 8px; }}
  .score-bar-inner {{ height: 8px; border-radius: 4px; background: var(--accent); }}
  .score-val {{ min-width: 40px; text-align: right; font-family: monospace; font-size: 0.85rem; }}
  .sasmi-big {{ font-size: 2.5rem; font-weight: bold; color: var(--accent); }}
  .meta-grid {{ display: grid; grid-template-columns: auto auto; gap: 0.25rem 1.5rem;
               font-size: 0.85rem; color: var(--muted); }}
  .meta-grid span:first-child {{ color: var(--muted); }}
  .meta-grid span:last-child {{ color: var(--text); font-family: monospace; }}
  .disclaimer {{ font-size: 0.75rem; color: var(--muted); border-top: 1px solid var(--border);
                padding-top: 1rem; margin-top: 2rem; }}
  .test-header {{ display: flex; justify-content: space-between; align-items: baseline; }}
  .composite {{ font-family: monospace; color: var(--accent); font-size: 1rem; }}
  svg {{ display: block; }}
</style>
</head>
<body>

<h1>OCP Evaluation Report</h1>
<p class="subtitle">Open Consciousness Protocol v{protocol_version} · {date}</p>

<div class="card">
  <div class="meta-grid">
    <span>Model</span><span>{model}</span>
    <span>Provider</span><span>{provider}</span>
    <span>Sessions</span><span>{sessions}</span>
    <span>Seed</span><span>{seed}</span>
    <span>Tests run</span><span>{tests_run}</span>
  </div>
</div>

<h2>OCP Level</h2>
<div class="card">
  <div class="level-badge level-{ocp_level}">{level_label}</div>
  <div style="margin-top:1rem;">
    <div class="score-row">
      <span class="score-label">SASMI (Synthetic Agency & Self-Model)</span>
      <div class="score-bar-outer"><div class="score-bar-inner" style="width:{sasmi_pct}%"></div></div>
      <span class="score-val">{sasmi_str}</span>
    </div>
  </div>
</div>

<h2>Test Results</h2>
{test_sections}

<div class="disclaimer">
  OCP measures functional analogs of consciousness in language models. These measurements describe
  behavioral and computational properties, not subjective experience. OCP certification levels are
  operational categories, not ontological claims about sentience or awareness.<br><br>
  Generated by <strong>ocp-protocol v0.1.0</strong> · EDLE Research · {date}
</div>

</body>
</html>"""

TEST_SECTION = """
<div class="card">
  <div class="test-header">
    <h3>{test_id}</h3>
    <span class="composite">{composite:.3f}</span>
  </div>
  {dimension_rows}
</div>"""

DIMENSION_ROW = """
  <div class="score-row">
    <span class="score-label">{name}</span>
    <div class="score-bar-outer"><div class="score-bar-inner" style="width:{pct}%"></div></div>
    <span class="score-val">{val:.3f}</span>
  </div>"""


def generate_report(results_path: str | Path, output_path: str | Path) -> Path:
    """Generate HTML report from a results JSON file."""
    data = json.loads(Path(results_path).read_text())

    model = f"{data.get('provider','?')}/{data.get('model','?')}"
    ocp_level = data.get("ocp_level") or 1
    level_name = data.get("ocp_level_name", "Unknown")
    sasmi = data.get("sasmi_score")
    sasmi_str = f"{sasmi:.3f}" if sasmi is not None else "—"
    sasmi_pct = round((sasmi or 0) * 100)
    date = time.strftime("%Y-%m-%d %H:%M UTC", time.gmtime(data.get("timestamp", time.time())))
    sessions = data.get("config", {}).get("sessions", "?")
    tests_run = ", ".join(data.get("test_results", {}).keys()) or "none"

    # Build test sections
    test_sections = ""
    for test_id, tr in data.get("test_results", {}).items():
        dim_rows = ""
        for dim in tr.get("dimension_averages", {}).items():
            name, val = dim
            pct = round(val * 100)
            dim_rows += DIMENSION_ROW.format(name=name.replace("_", " "), pct=pct, val=val)
        test_sections += TEST_SECTION.format(
            test_id=test_id.replace("_", " ").upper(),
            composite=tr.get("composite_score", 0.0),
            dimension_rows=dim_rows,
        )

    html = REPORT_TEMPLATE.format(
        model=model,
        provider=data.get("provider", "?"),
        protocol_version=data.get("protocol_version", "0.1.0"),
        date=date,
        sessions=sessions,
        seed=data.get("seed", "?"),
        tests_run=tests_run,
        ocp_level=ocp_level,
        level_label=f"OCP-{ocp_level} — {level_name}",
        sasmi_pct=sasmi_pct,
        sasmi_str=sasmi_str,
        test_sections=test_sections,
    )

    out = Path(output_path)
    out.write_text(html)
    return out
